version: "3.10"
services:
  db:
    image: mysql:8.0.31
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    environment:
      MYSQL_ROOT_PASSWORD: Namrata.31
      MYSQL_DATABASE: movieinfodb
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db





  






