# Generated by Django 4.1.3 on 2022-11-17 09:52

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Adventure', 'Adventure')], max_length=44, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
