# Generated by Django 4.1.3 on 2022-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_genres_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='type',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
